/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pets.and.vet;

import java.awt.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.AbstractBorder;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class receptionist_window extends javax.swing.JFrame {

    /**
     * Creates new form admin_window
     */
    DefaultTableModel dtm;
    Connection con = null;
    String f_name;
    String l_name;
    String col;
    String age;
    String gender;
    String phone;
    String email;
    String address;
    String type;
    String pet_id;
    String id_p;
    String app_id;
    public receptionist_window() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_and_vet", "root", "Root123456789@@");

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        dtm=new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("First Name");
        dtm.addColumn("Last Name");
        dtm.addColumn("Age");
        dtm.addColumn("Gender");
        dtm.addColumn("Type");
        dtm.addColumn("Color");
        dtm.addColumn("Phone");
        dtm.addColumn("Email");
        dtm.addColumn("Address");
        fill_table_model();
    }
    private void fill_table_model(){
        dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select * from appointments ");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(12), res.getString(1),res.getString(2),res.getInt(8),res.getString(9),res.getString(7),res.getString(10),res.getString(3),res.getString(4),res.getString(11)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
             Logger.getLogger(admin_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        fname_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        age_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gg = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gender_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        color_tf = new javax.swing.JTextField();
        pettype_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        viewlogs_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pett_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 119, 111));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Color", "Age", "Gender", "Phone", "Email", "Address", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        fname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_tfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Appointments List");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        gg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gg.setForeground(new java.awt.Color(255, 255, 255));
        gg.setText("Phone");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Color");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pet's Type");

        viewlogs_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewlogs_btn.setForeground(new java.awt.Color(16, 73, 68));
        viewlogs_btn.setText("View Logs");
        viewlogs_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlogs_btnActionPerformed(evt);
            }
        });

        edit_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(16, 73, 68));
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(16, 73, 68));
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        delete_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(16, 73, 68));
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pet ID");

        pett_id.setEditable(false);

        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(16, 76, 71));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(viewlogs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pett_id, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(16, 16, 16)
                                    .addComponent(fname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(67, 67, 67)
                                    .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(62, 62, 62)
                                    .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gender_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181))
                                .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))
                            .addComponent(color_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(gg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181))
                                .addComponent(pettype_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(color_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gg)
                            .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pettype_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(lname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(gender_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(address_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pett_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewlogs_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
         f_name=fname_tf.getText();
         l_name=lname_tf.getText();
         col=color_tf.getText();
         age=age_tf.getText();
         gender=gender_tf.getText();
         phone=phone_tf.getText();
         email=email_tf.getText();
         address=address_tf.getText();
         type=pettype_tf.getText();
        if(!f_name.isEmpty() && !l_name.isEmpty() && !col.isEmpty() && !age.isEmpty() && !gender.isEmpty() && !phone.isEmpty() && !email.isEmpty() && !address.isEmpty() && !type.isEmpty()){
            try {
                PreparedStatement stnt = con.prepareStatement("insert into owners (first_name,last_name,phone,ssn,email) values (?,?,?,?,?)");
                stnt.setString(1, f_name);
                stnt.setString(2, l_name);
                stnt.setString(3, phone);
                stnt.setString(4, "30304041402755");
                stnt.setString(5, email);
                stnt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
            }
            int idd=0;
            try {
                PreparedStatement stnt = con.prepareStatement("select * from owners");
                ResultSet res=stnt.executeQuery();
                while(res.next()){
                idd=res.getInt(1);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
            }
            String own_id=String.valueOf(idd);
            try {
                PreparedStatement st = con.prepareStatement("insert into pets (kind,color,age,gender,owner_id) values (?,?,?,?,?)");
                st.setString(1, type);
                st.setString(2, col);
                st.setString(3,age);
                st.setString(4, gender);
                st.setString(5, own_id);
                st.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
            }
             int iddd=0;
            try {
                PreparedStatement stnt = con.prepareStatement("select * from pets");
                ResultSet res=stnt.executeQuery();
                while(res.next()){
                iddd=res.getInt(1);
                }
                pet_id=String.valueOf((iddd));
            } catch (SQLException ex) {
                Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
            }
             try {
                 PreparedStatement snt = con.prepareStatement("insert into appointments (own_first_name,own_last_name,phone,email,owner_id,pet_id,kind,age,gender,color,address) values (?,?,?,?,?,?,?,?,?,?,?)");
                 snt.setString(1, f_name);
                 snt.setString(2, l_name);
                 snt.setString(3, phone);
                 snt.setString(4,email);
                 snt.setString(5, own_id);
                 snt.setString(6, pet_id);
                 snt.setString(7, type);
                 snt.setString(8, age);
                 snt.setString(9, gender);
                 snt.setString(10, col);
                 snt.setString(11, address);
                 snt.executeUpdate();
                 
             } catch (SQLException ex) {
                 Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
             }
             fill_table_model();
         fname_tf.setText("");
         lname_tf.setText("");
         color_tf.setText("");
         age_tf.setText("");
         gender_tf.setText("");
         phone_tf.setText("");
         email_tf.setText("");
         address_tf.setText("");
         pettype_tf.setText("");
         pett_id.setText("");
        }
        else {
        JOptionPane.showMessageDialog(this, "Please, Fill all cells");
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        String fname=fname_tf.getText();
        String lname=lname_tf.getText();
        String ema=email_tf.getText();
        String agge=age_tf.getText();
        String add=address_tf.getText();
        String pho=phone_tf.getText();
        String gen=gender_tf.getText();
        String iddd=pett_id.getText();
        String ty=pettype_tf.getText();
        String co=color_tf.getText();
         try {
             PreparedStatement s = con.prepareStatement("update appointments set own_first_name=? ,own_last_name=?,phone=?,email=?,kind=?,age=?,gender=?,color=?,address=? where pet_id= ?");
             s.setString(1, fname);
             s.setString(2, lname);
             s.setString(3, pho);
             s.setString(4, ema);
             s.setString(5, ty);
             s.setString(6, agge);
             s.setString(7, gen);
             s.setString(8, co);
             s.setString(9, add);
             s.setString(10, iddd);
             s.executeUpdate();
             fill_table_model();
             fname_tf.setText("");
         lname_tf.setText("");
         color_tf.setText("");
         age_tf.setText("");
         gender_tf.setText("");
         phone_tf.setText("");
         email_tf.setText("");
         address_tf.setText("");
         pettype_tf.setText("");
         pett_id.setText("");
         } catch (SQLException ex) {
             Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void viewlogs_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlogs_btnActionPerformed
        view_logs next_window = new view_logs();
        this.dispose();
        next_window.setVisible(true);
    }//GEN-LAST:event_viewlogs_btnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel obj=(DefaultTableModel) table.getModel();
        int index = table.getSelectedRow();
        app_id = obj.getValueAt(table.getSelectedRow(), 0).toString();
        int app = Integer.parseInt(app_id);
        try {
            PreparedStatement stmt= con.prepareStatement("select pet_id from appointments where app_id = ?");
            stmt.setInt(1, app);
            ResultSet r = stmt.executeQuery();
            while(r.next()){
                id_p = String.valueOf(r.getInt(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(receptionist_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        String f_name_e = obj.getValueAt(table.getSelectedRow(), 1).toString();
        String l_name_e = obj.getValueAt(table.getSelectedRow(), 2).toString();
        String email_e = obj.getValueAt(table.getSelectedRow(), 8).toString();
        String age_e = obj.getValueAt(table.getSelectedRow(), 3).toString();
        String phone_e =obj.getValueAt(table.getSelectedRow(), 7).toString();
        String address_e = obj.getValueAt(table.getSelectedRow(), 9).toString();
        String gender_e = obj.getValueAt(table.getSelectedRow(), 4).toString();
        String type_e = obj.getValueAt(table.getSelectedRow(), 5).toString();
        String color_e=obj.getValueAt(table.getSelectedRow(), 6).toString();
        
        fname_tf.setText(f_name_e);
        lname_tf.setText(l_name_e);
        email_tf.setText(email_e);
        age_tf.setText(age_e);
        address_tf.setText(address_e);
        phone_tf.setText(phone_e);
        gender_tf.setText(gender_e);
        pett_id.setText(id_p);
        pettype_tf.setText(type_e);
        color_tf.setText(color_e);
    }//GEN-LAST:event_tableMouseClicked

    private void fname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_tfActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        fname_tf.setText("");
         lname_tf.setText("");
         color_tf.setText("");
         age_tf.setText("");
         gender_tf.setText("");
         phone_tf.setText("");
         email_tf.setText("");
         address_tf.setText("");
         pettype_tf.setText("");
        pett_id.setText("");
        try {
            PreparedStatement st = con.prepareStatement("delete from appointments where pet_id = " + id_p);
            st.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(admin_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        fill_table_model();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login n=new Login();
        this.dispose();
        n.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receptionist_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receptionist_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receptionist_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receptionist_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receptionist_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_tf;
    private javax.swing.JTextField age_tf;
    private javax.swing.JTextField color_tf;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField email_tf;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JTextField gender_tf;
    private javax.swing.JLabel gg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JTextField pett_id;
    private javax.swing.JTextField pettype_tf;
    private javax.swing.JTextField phone_tf;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable table;
    private javax.swing.JButton viewlogs_btn;
    // End of variables declaration//GEN-END:variables
}
