/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pets.and.vet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author abdelrhmankrm
 */
public class view_logs extends javax.swing.JFrame {

    /**
     * Creates new form admin_window
     */
    DefaultTableModel dtm;
    Connection con = null;
//    String condition;
    public view_logs() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pet_and_vet", "root", "root");

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        dtm=new DefaultTableModel();
        dtm.addColumn("Pet ID");
        dtm.addColumn("Owner's name");
        dtm.addColumn("Phone");
        dtm.addColumn("Pet's Type");
        dtm.addColumn("Pets Condition");
        dtm.addColumn("Gender");
        fill_table_model();
    }
  
    private void fill_table_model(){
        dtm.setRowCount(0);
        
        try{
            PreparedStatement stmt;
            stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id");// Karam
          ResultSet res=stmt.executeQuery();
          while(res.next()){
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5), res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
             Logger.getLogger(admin_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
//     private void search(String x)
//    {
//        dtm.setRowCount(0);
//        try{
//          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where own_first_name like \""+x+"%\"");
//          ResultSet res=stmt.executeQuery();
//          while(res.next())
//          {
//              //cl_ids.add(res.getInt());
//              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(7),res.getString(6),res.getString(5)});
//              tbl_show.setModel(dtm);
//          }
//        }
//        catch (SQLException ex) {
//          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.println(ex);
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        pets = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        search_tf = new javax.swing.JTextField();
        clear_btn = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 119, 111));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet ID", "Owner's Name", "Phone", "Pet's Type", "Pet's Condition", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clinic Logs");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search By");

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(16, 76, 71));
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        modify.setForeground(new java.awt.Color(16, 76, 71));
        modify.setText("Modify Appointments");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        pets.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        pets.setForeground(new java.awt.Color(16, 76, 71));
        pets.setText("Pets Appointmenets");
        pets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petsActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Owner Name", "Type", "Condition", "Gender" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tfActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(16, 76, 71));
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(395, 395, 395)
                                .addComponent(pets, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modify))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(895, 895, 895))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(modify, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pets, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String search_by=jComboBox1.getSelectedItem().toString();
       String ss=search_tf.getText();
       if (search_by== "ID"){
       dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where a.pet_id like \""+ss+"%\"");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       }
       else if(search_by== "Owner Name"){
       dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where own_first_name like \""+ss+"%\"");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       }
       else if(search_by== "Type"){
       dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where kind like \""+ss+"%\"");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       }
       else if(search_by== "Gender"){
       dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where gender like \""+ss+"%\"");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       }
       else if(search_by== "Condition"){
       dtm.setRowCount(0);
        try{
          PreparedStatement stmt= con.prepareStatement("select a.pet_id, a.own_first_name, a.phone, a.kind, d.pet_condintion, a.gender from appointments a join diagnosis d on a.pet_id = d.pet_id where condition like \""+ss+"%\"");
          ResultSet res=stmt.executeQuery();
          while(res.next())
          {
              //cl_ids.add(res.getInt());
              dtm.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
              table.setModel(dtm);
          }
        }
        catch (SQLException ex) {
          //   Logger.getLogger(addclient.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
       }
//        PreparedStatement st = con.prepareStatement("select p.pet_id, o.first_name, o.phone, p.kind, d.diagnose, p.gender from ")
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("enter the password");
        if(s.equals("rec123")){
            receptionist_window n=new receptionist_window();
            this.dispose();
            n.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "wrong password");
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void petsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petsActionPerformed
        // TODO add your handling code here:
        String s = JOptionPane.showInputDialog("enter the password");
        if(s.equals("doc123")){
            doctor_window new_window = new doctor_window();
            this.dispose();
            new_window.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "wrong password");
        }
    }//GEN-LAST:event_petsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        search_tf.setText("");
        fill_table_model();
    }//GEN-LAST:event_clear_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_logs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton modify;
    private javax.swing.JButton pets;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField search_tf;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
